import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying Seesaw with account:", deployer.address);
  console.log("Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "MON");

  const Seesaw = await ethers.getContractFactory("Seesaw");
  const seesaw = await Seesaw.deploy();
  await seesaw.waitForDeployment();

  const address = await seesaw.getAddress();
  console.log("Seesaw deployed to:", address);

  // Write address + ABI to frontend lib
  const frontendLib = path.join(__dirname, "../../frontend/lib");
  if (fs.existsSync(frontendLib)) {
    const artifact = JSON.parse(
      fs.readFileSync(
        path.join(__dirname, "../artifacts/src/Seesaw.sol/Seesaw.json"),
        "utf8"
      )
    );

    const output = `// Auto-generated by deploy script
export const SEESAW_ADDRESS = "${address}" as const;
export const SEESAW_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
    fs.writeFileSync(path.join(frontendLib, "contracts.ts"), output);
    console.log("Updated frontend/lib/contracts.ts");
  }

  // Also write a .env snippet
  console.log("\n--- Add to frontend/.env.local ---");
  console.log(`NEXT_PUBLIC_SEESAW_ADDRESS=${address}`);
  console.log("----------------------------------\n");
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
